force-app/main/default/objects/PlatformEventLog__b/PlatformEventLog__b.object-meta.xml
<CustomObject>
    <label>Platform Event Log</label>
    <pluralLabel>Platform Event Logs</pluralLabel>
</CustomObject>

force-app/main/default/objects/PlatformEventLog__b/fields/EventCreatedDate__c.field-meta.xml
<CustomField>
    <fullName>EventCreatedDate__c</fullName>
    <description>PlatformEventCreated Date</description>
    <label>EventCreatedDate</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/PlatformEventLog__b/fields/EventJson__c.field-meta.xml
<CustomField>
    <fullName>EventJson__c</fullName>
    <label>PlatformEventJson</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PlatformEventLog__b/fields/EventUuid__c.field-meta.xml
<CustomField>
    <fullName>EventUuid__c</fullName>
    <label>EventUuid</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PlatformEventLog__b/fields/ReplayId__c.field-meta.xml
<CustomField>
    <fullName>ReplayId__c</fullName>
    <label>ReplayId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PlatformEventLog__b/fields/RequestId__c.field-meta.xml
<CustomField>
    <fullName>RequestId__c</fullName>
    <label>RequestId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PlatformEventLog__b/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Platform event type</description>
    <label>Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PlatformEventLog__b/fields/url__c.field-meta.xml
<CustomField>
    <fullName>url__c</fullName>
    <label>url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PlatformEventLogger.cls
public without sharing class PlatformEventLogger {
    private List<SObject> events;
    public PlatformEventLogger(List<SObject> events) {
        this.events = events;
    }

    public void flush() {
        List<PEWrapper> peEvents = PEWrapper.mapTo(this.events);
        List<PlatformEventLog__b> logs = new List<PlatformEventLog__b>();

        String currentRequestId = Request.getCurrent().getRequestId();
        for (PEWrapper w : peEvents) {
            PlatformEventLog__b log = new PlatformEventLog__b();
            log.CreatedById__c = w.createdById;
            log.EventUuid__c = w.EventUuid.left(PlatformEventLog__b.EventUuid__c.getDescribe().getLength());
            log.EventCreatedDate__c = w.createdDate;
            log.ReplayId__c = w.ReplayId.left(PlatformEventLog__b.ReplayId__c.getDescribe().getLength());
            log.EventJson__c = w.rawJSON.left(PlatformEventLog__b.EventJson__c.getDescribe().getLength());
            log.Type__c = w.type.left(PlatformEventLog__b.Type__c.getDescribe().getLength());
            log.url__c = w.url.left(PlatformEventLog__b.url__c.getDescribe().getLength());
            log.RequestId__c = currentRequestId.left(PlatformEventLog__b.RequestId__c.getDescribe().getLength());
            logs.add(log);
        }

        //TODO: Handle SaveResult
        Database.insertImmediate(logs);
    }

    @InvocableMethod(label='Log Platform Events' description='Log Platform events to generic log')
    public static void logEvents(List<SObject> events) {
        System.debug('doing somthing');
        System.debug(events);
        //new PlatformEventLogger(events).flush();
    }
}