force-app/sample/main/default/objects/CustomTestEvent__e/CustomTestEvent__e.object-meta.xml
<CustomObject>
    <description>This is a custom event for example purposes</description>
    <label>CustomTestEvent</label>
    <pluralLabel>CustomTestEvents</pluralLabel>
</CustomObject>

force-app/sample/main/default/objects/CustomTestEvent__e/fields/CustomTextField__c.field-meta.xml
<CustomField>
    <fullName>CustomTextField__c</fullName>
    <description>This is a custom text field for example purposes</description>
    <label>CustomTextField</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/sample/main/default/classes/GenerateTestEvents.cls
public with sharing class GenerateTestEvents {
    public static void gernerateEvents(Integer numberOfEvents) {
        List<CustomTestEvent__e> events = new List<CustomTestEvent__e>();
        for (Integer i = 0; i < numberOfEvents; i++) {
            CustomTestEvent__e n = new CustomTestEvent__e();
            n.CustomTextField__c = 'generatedevent_' + datetime.now() + '_' + i;
            events.add(n);
        }

        System.debug(JSON.serialize(Eventbus.publish(events)));
    }
}